### ISSUE TITLE
fix: Jetstream dispatcher fails with panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by metacoma** [knative-extensions/eventing-natss#519]
**Describe the bug**
Dispatcher fails with panic:
```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1803016]

goroutine 133 [running]:
knative.dev/eventing-natss/pkg/channel/jetstream/utils.parseBackoffFuncAndDelay(0x1a498a0?)
        knative.dev/eventing-natss/pkg/channel/jetstream/utils/consumerconfig.go:148 +0x16
knative.dev/eventing-natss/pkg/channel/jetstream/utils.CalculateNakDelayForRetryNumber(0x1f70ac0?, 0xc0008dc090?)
        knative.dev/eventing-natss/pkg/channel/jetstream/utils/consumerconfig.go:109 +0x1b
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*NatsMessageDispatcherImpl).processDispatchResult(0xc0001289a8, {0x1f8eab8, 0xc0007bd8c0}, 0xc0001289a8?, 0x1f8eab8?, 0xc0007bd710?, 0xc0007bd890?, {0x1f6ece0?, 0xc0004d3120?})
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/message_dispatcher.go:229 +0x75a
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*NatsMessageDispatcherImpl).DispatchMessageWithNatsRetries(0xc0001289a8, {0x1f8eab8, 0xc0007bd710}, {0x1f8ea48, 0xc00096b2a0}, 0xc0007bd770, 0xc0000d73b0, 0xc0000d7440, 0xc0000d74d0, 0xc0004e1f40, ...)
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/message_dispatcher.go:142 +0xf8a
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*Consumer).doHandle(0xc0003961e0, {0x1f8eab8, 0xc0007bd710}, 0xc0001bc000)
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/consumer.go:119 +0x659
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*Consumer).MsgHandler.func1()
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/consumer.go:78 +0x13d
created by knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*Consumer).MsgHandler in goroutine 119
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/consumer.go:74 +0x67
```

 **Expected behavior**
 The message should be delivered to Knative Eventing.

 **To Reproduce**
<details><summary>bob.json</summary>
<p>
{
    "knativebrokerttl":"255",
    "specversion" : "1.0",
    "type" : "io-document",
    "source" : "/apis/v1/namespaces/default/ping",
    "subject" : "bob.laptop.tmux.default.foobar.42",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "datacontenttype" : "application/json",
    "data" : {
        "ps1_start": "user@mindwm-dev1:/home/user$",
        "ps1_end": "mindwm-client-e3168b3e-dc6f-11ee-a11d-8f9d41316c00",
        "input": "docker ps",
        "output": "CONTAINER ID   IMAGE                           COMMAND                  CREATED        STATUS        PORTS     NAMES\nc262a8b3ffe9   catthehacker/ubuntu:act-22.04   \"tail -f /dev/null\"      17 hours ago   Up 17 hours             act-build-act-yaml-apply-cfea7ea99cb09115e5339bf380d4d4d4e801c8485e41b7af87a5afe0f52bdce5\nb0dca6d6255f   16baf1d54ec7                    \"/usr/bin/docker-ent…\"   12 days ago    Up 17 hours             minio\n"
    }
}
</p>
</details>

```shell
$ cat bob.json | jq | nats pub mindwm.user.mindwm-dev1.abc
13:07:50 Reading payload from STDIN
13:07:50 Published 902 bytes to "mindwm.user.mindwm-dev1.abc"
$ cat bob.json | jq | nats pub mindwm.user.mindwm-dev1.abc
13:07:51 Reading payload from STDIN
13:07:51 Published 902 bytes to "mindwm.user.mindwm-dev1.abc"
$ cat bob.json | jq | nats pub mindwm.user.mindwm-dev1.abc
13:07:51 Reading payload from STDIN
13:07:51 Published 902 bytes to "mindwm.user.mindwm-dev1.abc"
```

 **Knative release version**
knative: 1.12.3
eventing-jsm.yaml: 1.10.7

 
 **Additional context**
pod jetstream-ch-dispatcher lifecycle while error `kubectl get pods -w ..`
 
```
jetstream-ch-controller-877d7f697-fggk8    1/1     Running   0               16h
jetstream-ch-dispatcher-674c49f67b-fwmpd   1/1     Running   9 (5m17s ago)   15h
jetstream-ch-dispatcher-674c49f67b-fwmpd   0/1     Error     9 (5m52s ago)   15h
jetstream-ch-dispatcher-674c49f67b-fwmpd   0/1     CrashLoopBackOff   9 (13s ago)     15h
jetstream-ch-dispatcher-674c49f67b-fwmpd                   1/1     Running             10 (5m9s ago)   15h
jetstream-ch-dispatcher-674c49f67b-fwmpd                   0/1     Error               10 (5m14s ago)   15h
jetstream-ch-dispatcher-674c49f67b-fwmpd                   0/1     CrashLoopBackOff    10 (14s ago)     15h
```
<details><summary>jetstream-ch-dispatcher log</summary>
<p>

{"level":"warn","ts":"2024-03-09T12:59:28.883Z","logger":"jetstream-channel-dispatcher","caller":"dispatcher/consumer.go:109","msg":"Cannot parse the spancontext, creating a new span","commit":"44752ad-dirty","knative.dev/pod":"jetstream-ch-dispatcher-674c49f67b-fwmpd","knative.dev/controller":"knative.dev.eventing-natss.pkg.channel.jetstream.dispatcher.Reconciler","knative.dev/kind":"messaging.knative.dev.NatsJetStreamChannel","knative.dev/traceid":"de6cf57a-c425-4590-af73-e4cb7a6ef985","knative.dev/key":"ksandbox/mindwmbroker-kne-trigger","is_leader":false,"is_leader":false,"sub_uid":"026196f7-fe3b-491c-a852-949e605d3bce"}
{"level":"info","ts":"2024-03-09T12:59:28.883Z","logger":"jetstream-channel-dispatcher","caller":"controller/controller.go:550","msg":"Reconcile succeeded","commit":"44752ad-dirty","knative.dev/pod":"jetstream-ch-dispatcher-674c49f67b-fwmpd","knative.dev/controller":"knative.dev.eventing-natss.pkg.channel.jetstream.dispatcher.Reconciler","knative.dev/kind":"messaging.knative.dev.NatsJetStreamChannel","knative.dev/traceid":"de6cf57a-c425-4590-af73-e4cb7a6ef985","knative.dev/key":"ksandbox/mindwmbroker-kne-trigger","duration":0.002935707}
{"level":"warn","ts":"2024-03-09T12:59:28.884Z","logger":"jetstream-channel-dispatcher","caller":"dispatcher/consumer.go:109","msg":"Cannot parse the spancontext, creating a new span","commit":"44752ad-dirty","knative.dev/pod":"jetstream-ch-dispatcher-674c49f67b-fwmpd","knative.dev/controller":"knative.dev.eventing-natss.pkg.channel.jetstream.dispatcher.Reconciler","knative.dev/kind":"messaging.knative.dev.NatsJetStreamChannel","knative.dev/traceid":"de6cf57a-c425-4590-af73-e4cb7a6ef985","knative.dev/key":"ksandbox/mindwmbroker-kne-trigger","is_leader":false,"is_leader":false,"sub_uid":"29c2eb36-0a62-44db-8459-8f5e9db05029"}
{"level":"error","ts":"2024-03-09T12:59:32.827Z","logger":"jetstream-channel-dispatcher","caller":"dispatcher/message_dispatcher.go:210","msg":"failed to execute message","commit":"44752ad-dirty","knative.dev/pod":"jetstream-ch-dispatcher-674c49f67b-fwmpd","error":"unexpected HTTP response, expected 2xx, got 502","dispatch_resp_code":502,"stacktrace":"knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*NatsMessageDispatcherImpl).processDispatchResult\n\tknative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/message_dispatcher.go:210\nknative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*NatsMessageDispatcherImpl).DispatchMessageWithNatsRetries\n\tknative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/message_dispatcher.go:142\nknative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*Consumer).doHandle\n\tknative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/consumer.go:119\nknative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*Consumer).MsgHandler.func1\n\tknative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/consumer.go:78"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1803016]

goroutine 99 [running]:
knative.dev/eventing-natss/pkg/channel/jetstream/utils.parseBackoffFuncAndDelay(0x1a498a0?)
        knative.dev/eventing-natss/pkg/channel/jetstream/utils/consumerconfig.go:148 +0x16
knative.dev/eventing-natss/pkg/channel/jetstream/utils.CalculateNakDelayForRetryNumber(0x1f70ac0?, 0xc00030ad80?)
        knative.dev/eventing-natss/pkg/channel/jetstream/utils/consumerconfig.go:109 +0x1b
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*NatsMessageDispatcherImpl).processDispatchResult(0xc0000103a8, {0x1f8eab8, 0xc0006131a0}, 0xc0000103a8?, 0x1f8eab8?, 0xc000612ff0?, 0xc000613170?, {0x1f6ece0?, 0xc00040ae10?})
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/message_dispatcher.go:229 +0x75a
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*NatsMessageDispatcherImpl).DispatchMessageWithNatsRetries(0xc0000103a8, {0x1f8eab8, 0xc000612ff0}, {0x1f8ea48, 0xc00040a750}, 0xc000613050, 0xc000484a20, 0xc000484ab0, 0xc000484b40, 0xc000527680, ...)
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/message_dispatcher.go:142 +0xf8a
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*Consumer).doHandle(0xc0000d23c0, {0x1f8eab8, 0xc000612ff0}, 0xc000180930)
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/consumer.go:119 +0x659
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*Consumer).MsgHandler.func1()
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/consumer.go:78 +0x13d
created by knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*Consumer).MsgHandler in goroutine 145
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/consumer.go:74 +0x67
</p>
</details>

**Comment by metacoma** [comment]
I've discovered that the panic occurs only when there are errors `received a non-empty response not recognized as CloudEvent. The response MUST be either empty or a valid CloudEvent` in mq_broker_filter pod
 
```json
{
  "level": "error",
  "ts": "2024-03-09T13:27:41.373Z",
  "logger": "mt_broker_filter",
  "caller": "filter/filter_handler.go:287",
  "msg": "failed to write response",
  "commit": "cb5dfda",
  "error": "received a non-empty response not recognized as CloudEvent. The response MUST be either empty or a valid CloudEvent",
  "stacktrace": "knative.dev/eventing/pkg/broker/filter.(*Handler).send\n\tknative.dev/eventing/pkg/broker/filter/filter_handler.go:287\nknative.dev/eventing/pkg/broker/filter.(*Handler).ServeHTTP\n\tknative.dev/eventing/pkg/broker/filter/filter_handler.go:237\nknative.dev/eventing/pkg/eventingtls.(*ServerManager).StartServers.func1.(*ServerManager).httpHandler.func1\n\tknative.dev/eventing/pkg/eventingtls/servermanager.go:102\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2136\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\tgo.opencensus.io@v0.24.0/plugin/ochttp/server.go:92\nknative.dev/pkg/network/handlers.(*Drainer).ServeHTTP\n\tknative.dev/pkg@v0.0.0-20231023151236-29775d7c9e5c/network/handlers/drain.go:113\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2938\nnet/http.(*conn).serve\n\tnet/http/server.go:2009"
}
```

After i changed knative service code from
```python
return "{}", 200
```
to
```python
return "{}", 200
```

the go panics inside jsm-dispatcher disappeared, and the dispatcher works fine

**Comment by astelmashenko** [comment]
Please try to specify delivery configuration in your subscription/trigger, like below
```
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: display-sub
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: NatsJetStreamChannel
    name: my-channel
  delivery:
    backoffDelay: PT0.2S
    backoffPolicy: linear
    retry: 4
    timeout: PT40S
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
```
